* long-line

An Emacs minor mode which show or hide indicator depending whether the buffer contain lines longer then value of ~fill-column~.

** Requirements

- Emacs Emacs 27.1

** Installation

*** with straight-use-package

Put the following in your init file:

#+begin_src elisp
(use-package long-line
  :straight (long-line
             :type git
             :host github
             :repo "KarimAziev/long-line")
  :hook ((emacs-lisp-mode . long-line-mode)))
#+end_src

*** Manual

Or download repository and add it to your ~load-path~.

#+begin_src elisp

(add-to-list 'load-path "/path/to/long-line/")

(require 'long-line)
(add-hook 'emacs-lisp-mode-hook 'long-line-mode)
#+end_src

** Minor mode

*** ~long-line-mode~
Show or hide fill column indicator after save. If buffer contain lines longer then the value of the variable =fill-column= show it, else hide.
** Commands

*** ~long-line-show-or-hide-indicator~
Show or hide fill column indicator in current buffer. If buffer contain lines longer then the value of the variable =fill-column= show it, else hide.
*** ~long-line-next-long-line~  (&optional arg)
Move to the ARGth next long line greater than =fill-column=.
*** ~long-line-prev-long-line~
Move to the previous long line greater than =fill-column=.
*** ~long-line-next-or-prev-long~
Move to the next or previous long line greater than =fill-column=.
*** ~long-line-prev-or-next-long~
Move to the previous or next long line greater than =fill-column=.
** Customization

*** ~long-line-highlight-line-p~
Whether to highlight long line after =long-line-next-long-line=.
*** ~long-line-message-function~
Function to show messages. Should accept the same arguments as =message=.

** Variables

*** ~long-line-doc~

